# Generated by Django 4.2.5 on 2023-10-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuil_cuit',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Cuil/Cuit'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='metrosCuadrados',
            field=models.IntegerField(verbose_name='Metros Cuadrados'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nroAmbientes',
            field=models.IntegerField(verbose_name='Numero de ambientes'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioUnitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario'),
        ),
    ]
