# Generated by Django 4.2.5 on 2023-10-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuil_cuit',
            field=models.CharField(max_length=14, unique=True, verbose_name='Cuil/Cuit'),
        ),
    ]
