# Generated by Django 4.2.5 on 2023-10-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_cuil_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuil_cuit',
            field=models.CharField(max_length=13, unique=True, verbose_name='Cuil/Cuit'),
        ),
    ]
