# Generated by Django 4.2.5 on 2023-11-02 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('fechaEstimadaComienzo', models.DateField()),
                ('fechaEstimadaFinalizacion', models.DateField()),
                ('cantidadEstimadaEmpleados', models.IntegerField()),
                ('importeTotalEstimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importeTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metrosCuadrados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidadDeMedida', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tiposervicio')),
            ],
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='productos',
            field=models.ManyToManyField(through='servicios.TipoServicioProducto', to='core.producto'),
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('presupuestado', 'Presupuestado'), ('contratado', 'Contratado 🛸'), ('vencido', 'Vencido 👽'), ('cancelado', 'Cancelado 💩'), ('pagado', 'Pagado'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='servicios.servicio')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoServicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tiposervicio')),
            ],
        ),
    ]
