# Generated by Django 4.2.5 on 2023-11-06 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costoServicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unidadDeMedida', models.CharField(max_length=30, verbose_name='Unidad de medida')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_cantidad', to='servicios.tiposervicio')),
            ],
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='productos',
            field=models.ManyToManyField(through='servicios.TipoServicioProducto', to='core.producto'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateField(null=True)),
                ('cantidadEstimadaEmpleados', models.IntegerField()),
                ('ajuste', models.IntegerField()),
                ('metrosCuadrados', models.IntegerField()),
                ('detalleServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='servicios.detalleservicio')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('presupuestado', 'Presupuestado 👽'), ('contratado', 'Contratado 🛸'), ('vencido', 'Vencido 💀'), ('cancelado', 'Cancelado 💩'), ('pagado', 'Pagado 🤑'), ('iniciado', 'Iniciado 😊'), ('finalizado', 'Finalizado 😴')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='servicios.servicio')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='tipoServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='servicios.tiposervicio'),
        ),
    ]
