# Generated by Django 4.2.5 on 2023-10-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='unidadDeMedida',
            field=models.CharField(max_length=30, verbose_name='Unidad de medida'),
        ),
    ]
