# Generated by Django 4.2.5 on 2023-11-27 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='diasSemana',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)], verbose_name='Dias por semana estimados'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiposervicioproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de m² por dia '),
        ),
    ]
