# Generated by Django 4.2.5 on 2025-01-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000000000000000000000000),
        ),
    ]
