# Generated by Django 4.2.5 on 2023-11-10 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_remove_tiposervicio_unidaddemedida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleservicio',
            name='costoServicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='detalleServicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='metrosCuadrados',
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='servicio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='servicios.servicio'),
            preserve_default=False,
        ),
    ]
