# Generated by Django 4.2.5 on 2023-11-17 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_servicio_desde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposervicio',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='ganancia',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
