# Generated by Django 4.2.5 on 2023-11-23 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_servicio_desde'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('presupuestado', 'Presupuestado 👽'), ('contratado', 'Contratado 🛸'), ('vencido', 'Vencido 💀'), ('cancelado', 'Cancelado 💩'), ('pagado', 'Pagado 🤑'), ('iniciado', 'Iniciado 😊'), ('finalizado', 'Finalizado 😴')], default='presupuestado', max_length=20),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad de m²'),
        ),
        migrations.AlterField(
            model_name='detalleservicio',
            name='tipoServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='servicios.tiposervicio', verbose_name='Tipo Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cantidadEstimadaEmpleados',
            field=models.IntegerField(verbose_name='Empleados Estimados'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='desde',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='hasta',
            field=models.DateField(null=True, verbose_name='Fecha Fin'),
        ),
    ]
