# Generated by Django 4.2.5 on 2023-11-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_remove_tiposervicio_codigo_and_more'),
        ('servicios', '0006_servicio_estado_alter_detalleservicio_cantidad_and_more'),
    ]

    operations = [
    ]
