# Generated by Django 4.2.5 on 2023-11-26 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_merge_20231126_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleservicio',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de m²'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='ajuste',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cantidadEstimadaEmpleados',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(1)], verbose_name='Empleados Estimados'),
        ),
    ]
