# Generated by Django 4.2.5 on 2023-09-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuil_cuit',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]

    '''
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),'''
