# Generated by Django 4.2.5 on 2023-10-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoAbonado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaPago', models.DateField()),
                ('formaPago', models.CharField(choices=[('efectivo', 'efectivo'), ('credito', 'credito'), ('cheque', 'cheque'), ('transferencia', 'transferencia')], default='efectivo', max_length=15)),
            ],
        ),
    ]
