# Generated by Django 4.2.5 on 2023-11-30 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_diassemana_and_more'),
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
        migrations.AlterField(
            model_name='factura',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_servicio', to='servicios.servicio'),
        ),
    ]
