# Generated by Django 4.2.5 on 2023-11-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
