# Generated by Django 4.2.5 on 2023-12-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicio_total_alter_servicio_ajuste'),
        ('facturas', '0002_remove_factura_total_alter_factura_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='pagado',
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='servicios.servicio'),
        ),
    ]
